[package]
name = "imxrt-dcd-build-example"
version.workspace = true
edition = "2021"


[dependencies]

static-include-bytes = "2.0"

# internal
imxrt-dcd.workspace = true

[build-dependencies]

# internal
imxrt-dcd.workspace = true
