[package]
name = "imxrt-dcd-build-example"
version.workspace = true
edition = "2021"


[dependencies]
static-include-bytes = "2.0"
imxrt-dcd.workspace = true

[build-dependencies]
imxrt-dcd.workspace = true
imxrt-ral.workspace = true
