[package]
name = "imxrt-dcd-build-example"
version = "1.0.0"
edition = "2021"


[dependencies]

static-include-bytes = "1.0.0"

# internal
imxrt-dcd = { path = "../imxrt-dcd", version = "1.0.0" }

[build-dependencies]

# internal
imxrt-dcd = { path = "../imxrt-dcd", version = "1.0.0" }
